"""empty message

Revision ID: 0f60286f4a6c
Revises: a9fb7c34ef0d
Create Date: 2025-04-05 18:37:55.837411

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0f60286f4a6c"
down_revision = "a9fb7c34ef0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("auto_booking_rules", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("supplier_id", sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column("text_pattern", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("account_id", sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column("tax_rate_id", sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column("active", sa.Boolean(), nullable=False))
        batch_op.drop_constraint(
            "auto_booking_rules_default_tax_rate_id_fkey", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "auto_booking_rules_default_account_id_fkey", type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "suppliers", ["supplier_id"], ["id"])
        batch_op.create_foreign_key(None, "accounts", ["account_id"], ["id"])
        batch_op.create_foreign_key(None, "tax_rates", ["tax_rate_id"], ["id"])
        batch_op.drop_column("default_tax_rate_id")
        batch_op.drop_column("match_string")
        batch_op.drop_column("default_account_id")

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("color", sa.String(), nullable=True))

    with op.batch_alter_table("chart_of_accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))

    with op.batch_alter_table("cost_centers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("code", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("active", sa.Boolean(), nullable=False))

    with op.batch_alter_table("currencies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_default", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))

    with op.batch_alter_table("document_tags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.UUID(), nullable=False))

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("document_number", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("contact_id", sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column("issue_date", sa.Date(), nullable=False))
        batch_op.add_column(sa.Column("net_amount", sa.Numeric(), nullable=False))
        batch_op.add_column(sa.Column("tax_amount", sa.Numeric(), nullable=False))
        batch_op.add_column(sa.Column("total_amount", sa.Numeric(), nullable=False))
        batch_op.add_column(sa.Column("currency_id", sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column("is_posted", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(
            "uq_document_number_type", ["document_number", "document_type"]
        )
        batch_op.drop_constraint("documents_link_id_fkey", type_="foreignkey")
        batch_op.drop_constraint("documents_cost_center_id_fkey", type_="foreignkey")
        batch_op.drop_constraint("documents_user_id_fkey", type_="foreignkey")
        # Fremdschlüssel documents_currency_code_fkey wurde bereits in der vorherigen Migration entfernt
        batch_op.create_foreign_key(None, "contacts", ["contact_id"], ["id"])
        batch_op.create_foreign_key(None, "currencies", ["currency_id"], ["id"])
        batch_op.drop_column("cost_center_id")
        batch_op.drop_column("delivery_date")
        batch_op.drop_column("link_id")
        batch_op.drop_column("document_date")
        batch_op.drop_column("user_id")
        batch_op.drop_column("number")
        batch_op.drop_column("currency_code")

    with op.batch_alter_table("links", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source_document_id", sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column("target_document_id", sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column("link_type", sa.String(), nullable=False))
        batch_op.create_foreign_key(None, "documents", ["target_document_id"], ["id"])
        batch_op.create_foreign_key(None, "documents", ["source_document_id"], ["id"])

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.add_column(sa.Column("color", sa.String(), nullable=True))

    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_data", sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column("user_id", sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column("processed", sa.Boolean(), nullable=False))
        batch_op.alter_column("document_id", existing_type=sa.UUID(), nullable=True)
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])
        batch_op.drop_column("file_size")
        batch_op.drop_column("file_content")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("file_content", sa.TEXT(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("file_size", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("document_id", existing_type=sa.UUID(), nullable=False)
        batch_op.drop_column("processed")
        batch_op.drop_column("user_id")
        batch_op.drop_column("file_data")

    with op.batch_alter_table("tags", schema=None) as batch_op:
        batch_op.drop_column("color")

    with op.batch_alter_table("links", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("link_type")
        batch_op.drop_column("target_document_id")
        batch_op.drop_column("source_document_id")

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "currency_code", sa.CHAR(length=3), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("number", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("document_date", sa.DATE(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("link_id", sa.UUID(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("delivery_date", sa.DATE(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("cost_center_id", sa.UUID(), autoincrement=False, nullable=True)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "documents_currency_code_fkey", "currencies", ["currency_code"], ["code"]
        )
        batch_op.create_foreign_key(
            "documents_user_id_fkey", "users", ["user_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "documents_cost_center_id_fkey", "cost_centers", ["cost_center_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "documents_link_id_fkey", "links", ["link_id"], ["id"]
        )
        batch_op.drop_constraint("uq_document_number_type", type_="unique")
        batch_op.drop_column("created_at")
        batch_op.drop_column("is_posted")
        batch_op.drop_column("currency_id")
        batch_op.drop_column("total_amount")
        batch_op.drop_column("tax_amount")
        batch_op.drop_column("net_amount")
        batch_op.drop_column("issue_date")
        batch_op.drop_column("contact_id")
        batch_op.drop_column("document_number")

    with op.batch_alter_table("document_tags", schema=None) as batch_op:
        batch_op.drop_column("id")

    with op.batch_alter_table("currencies", schema=None) as batch_op:
        batch_op.drop_column("is_active")
        batch_op.drop_column("is_default")

    with op.batch_alter_table("cost_centers", schema=None) as batch_op:
        batch_op.drop_column("active")
        batch_op.drop_column("code")

    with op.batch_alter_table("chart_of_accounts", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_column("color")

    with op.batch_alter_table("auto_booking_rules", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "default_account_id", sa.UUID(), autoincrement=False, nullable=True
            )
        )
        batch_op.add_column(
            sa.Column("match_string", sa.VARCHAR(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "default_tax_rate_id", sa.UUID(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            "auto_booking_rules_default_account_id_fkey",
            "accounts",
            ["default_account_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "auto_booking_rules_default_tax_rate_id_fkey",
            "tax_rates",
            ["default_tax_rate_id"],
            ["id"],
        )
        batch_op.drop_column("active")
        batch_op.drop_column("tax_rate_id")
        batch_op.drop_column("account_id")
        batch_op.drop_column("text_pattern")
        batch_op.drop_column("supplier_id")
        batch_op.drop_column("description")
        batch_op.drop_column("name")

    # ### end Alembic commands ###
