"""empty message

Revision ID: 25e0db94f681
Revises: f01b8ff06c49
Create Date: 2025-04-06 15:56:52.029453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25e0db94f681'
down_revision = 'f01b8ff06c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint('uq_document_number_type', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_document_number_type', ['document_number', 'document_type'])

    # ### end Alembic commands ###
