"""empty message

Revision ID: 33d30acc5427
Revises: 8d2afeb57980
Create Date: 2025-04-06 14:28:51.066843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d30acc5427'
down_revision = '8d2afeb57980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('total_amount')
        batch_op.drop_column('net_amount')
        batch_op.drop_column('tax_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_amount', sa.NUMERIC(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('net_amount', sa.NUMERIC(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_amount', sa.NUMERIC(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
