"""empty message

Revision ID: 5a8ca378fb6e
Revises: 91b6b8e5a96b
Create Date: 2025-04-08 12:00:33.096505

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a8ca378fb6e'
down_revision = '91b6b8e5a96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_explanations')
    op.drop_table('account_hierarchies')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chart_of_accounts_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'chart_of_accounts', ['chart_of_accounts_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('chart_of_accounts_id')

    op.create_table('account_hierarchies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('class_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('class_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('related_accounts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='account_hierarchies_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='account_hierarchies_pkey')
    )
    op.create_table('account_explanations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='account_explanations_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='account_explanations_pkey')
    )
    # ### end Alembic commands ###
