"""Initial migration

Revision ID: b3abfce92ecb
Revises: 
Create Date: 2025-03-30 17:00:49.520376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3abfce92ecb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('account',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('nummer', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_path', sa.String(length=500), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('beleg_datum', sa.Date(), nullable=True),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('kategorie_id', sa.UUID(), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('steuerart', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['kategorie_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('art', sa.String(length=10), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('konto_id', sa.UUID(), nullable=True),
    sa.Column('gegenkonto', sa.String(length=100), nullable=True),
    sa.Column('kategorie_id', sa.UUID(), nullable=True),
    sa.Column('beleg_id', sa.UUID(), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['beleg_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['kategorie_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['konto_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    op.drop_table('document')
    op.drop_table('category')
    op.drop_table('account')
    op.drop_table('user')
    # ### end Alembic commands ###
