"""empty message

Revision ID: b7b2dec85346
Revises: e60872fb9fc7
Create Date: 2025-04-10 18:33:30.799432

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7b2dec85346'
down_revision = 'e60872fb9fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_hierarchies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_hierarchies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('class_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('class_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('group_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('related_accounts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='account_hierarchies_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='account_hierarchies_pkey')
    )
    # ### end Alembic commands ###
