"""Remove file_path field and make file_content required

Revision ID: ce3f67629bcf
Revises: c5354812361e
Create Date: 2025-04-05 15:37:55.060757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce3f67629bcf'
down_revision = 'c5354812361e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'accounts', ['parent_id'], ['id'])

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_content', sa.Text(), nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('file_content')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('level')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
