"""empty message

Revision ID: d4b5a5c3878d
Revises: 64d243b2501c
Create Date: 2025-04-01 12:45:36.529274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4b5a5c3878d'
down_revision = '64d243b2501c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.alter_column('tax_rate_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('tax_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tax_rate', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.alter_column('tax_rate_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
