"""Add tax_rate_id to Account model

Revision ID: db0c712f55d9
Revises: 0f60286f4a6c
Create Date: 2025-04-05 20:47:17.443561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0c712f55d9'
down_revision = '0f60286f4a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'tax_rates', ['tax_rate_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('tax_rate_id')

    # ### end Alembic commands ###
