"""empty message

Revision ID: f01b8ff06c49
Revises: 33d30acc5427
Create Date: 2025-04-06 14:38:33.512624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f01b8ff06c49'
down_revision = '33d30acc5427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.drop_constraint('line_items_account_id_fkey', type_='foreignkey')
        batch_op.drop_column('account_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('line_items_account_id_fkey', 'accounts', ['account_id'], ['id'])

    # ### end Alembic commands ###
