"""Add account hierarchy table and modify account model

Revision ID: f83294852080
Revises: 25e0db94f681
Create Date: 2025-04-08 10:27:27.645558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = 'f83294852080'
down_revision = '25e0db94f681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('account_class', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_group', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_type_custom', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('taxonomy_element', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('taxonomy_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('explanations', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('related_accounts', sa.JSON(), nullable=True))
        batch_op.drop_constraint('accounts_parent_id_fkey', type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('level')

    # Erstellen der account_hierarchies Tabelle
    op.create_table('account_hierarchies',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('account_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('class_number', sa.String(), nullable=True),
        sa.Column('class_name', sa.String(), nullable=True),
        sa.Column('group_number', sa.String(), nullable=True),
        sa.Column('group_name', sa.String(), nullable=True),
        sa.Column('type_number', sa.String(), nullable=True),
        sa.Column('type_name', sa.String(), nullable=True),
        sa.Column('related_accounts', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Löschen der account_hierarchies Tabelle
    op.drop_table('account_hierarchies')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('parent_id', postgresql.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('accounts_parent_id_fkey', 'accounts', ['parent_id'], ['id'])
        batch_op.drop_column('related_accounts')
        batch_op.drop_column('explanations')
        batch_op.drop_column('taxonomy_type')
        batch_op.drop_column('taxonomy_element')
        batch_op.drop_column('account_type_custom')
        batch_op.drop_column('account_group')
        batch_op.drop_column('account_class')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
